/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oas_project;

import javax.swing.JFrame;
import javax.swing.*;         // All Swing components like JFrame, JButton, JLabel, JTextField, JOptionPane
import java.awt.*;            // Layout managers like FlowLayout
import java.awt.event.*;      // Event handling like ActionListener, ActionEvent
import java.sql.*;            // JDBC classes like Connection, DriverManager, PreparedStatement, SQLException
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;


/**
 *
 * @author AykAyz
 */
public class AdmissionSlipForm extends javax.swing.JFrame {

    private ButtonGroup excusedUnexcused;
    private ButtonGroup offenseGroup;

    public AdmissionSlipForm() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);    
        initComponents();
        
        // Initialize the ButtonGroup
        excusedUnexcused = new ButtonGroup();
        excusedUnexcused.add(rbtnExcused);
        excusedUnexcused.add(rbtnUnexcused);
        
        offenseGroup = new ButtonGroup();
        offenseGroup.add(rbtnAbsent);
        offenseGroup.add(rbtnTardy);
        offenseGroup.add(rbtnCutting);
        
        cbxYear.setSelectedItem(null);
        cbxSection.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHdr1 = new javax.swing.JLabel();
        lblHdr2 = new javax.swing.JLabel();
        lblText1 = new javax.swing.JLabel();
        lblText2 = new javax.swing.JLabel();
        lblYrSec = new javax.swing.JLabel();
        cbxYear = new javax.swing.JComboBox<>();
        cbxSection = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblOffense = new javax.swing.JLabel();
        txtMinutes = new javax.swing.JTextField();
        txtClasses = new javax.swing.JTextField();
        txtDays = new javax.swing.JTextField();
        lblMinutes = new javax.swing.JLabel();
        lblDays = new javax.swing.JLabel();
        lblClasses = new javax.swing.JLabel();
        rbtnAbsent = new javax.swing.JRadioButton();
        rbtnTardy = new javax.swing.JRadioButton();
        rbtnCutting = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        txtGName = new javax.swing.JTextField();
        txtMI = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        lblGName = new javax.swing.JLabel();
        lblMI = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblSubjects = new javax.swing.JLabel();
        ckbxBio = new javax.swing.JCheckBox();
        ckbxChem = new javax.swing.JCheckBox();
        ckbxEng = new javax.swing.JCheckBox();
        ckbxFil = new javax.swing.JCheckBox();
        ckbxCS = new javax.swing.JCheckBox();
        ckbxMath = new javax.swing.JCheckBox();
        ckbxPEHM = new javax.swing.JCheckBox();
        ckbxPhy = new javax.swing.JCheckBox();
        ckbxSS = new javax.swing.JCheckBox();
        ckbxElective = new javax.swing.JCheckBox();
        ckbxValEd = new javax.swing.JCheckBox();
        ckbxRes = new javax.swing.JCheckBox();
        lblIncDates = new javax.swing.JLabel();
        txtIncDates = new javax.swing.JTextField();
        lblReason = new javax.swing.JLabel();
        lblAttach = new javax.swing.JLabel();
        ckbxMedCert = new javax.swing.JCheckBox();
        ckbxLetter = new javax.swing.JCheckBox();
        lblCertBy = new javax.swing.JLabel();
        ckbxHSU = new javax.swing.JCheckBox();
        ckbxGSU = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        lblDateIssued = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblMonth = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        rbtnExcused = new javax.swing.JRadioButton();
        rbtnUnexcused = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReason = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 539));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(206, 206, 206));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(906, 612));

        lblHdr1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHdr1.setForeground(new java.awt.Color(0, 0, 0));
        lblHdr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHdr1.setText("Philippine Science High School - ZRC");

        lblHdr2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHdr2.setForeground(new java.awt.Color(0, 0, 0));
        lblHdr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHdr2.setText("Class Admission Slip");

        lblText1.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        lblText1.setForeground(new java.awt.Color(0, 0, 0));
        lblText1.setText("To all teachers concerned:");

        lblText2.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        lblText2.setForeground(new java.awt.Color(0, 0, 0));
        lblText2.setText("Please admit");

        lblYrSec.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        lblYrSec.setForeground(new java.awt.Color(0, 0, 0));
        lblYrSec.setText("Year & Section:");

        cbxYear.setBackground(new java.awt.Color(255, 255, 255));
        cbxYear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxYear.setForeground(new java.awt.Color(0, 0, 0));
        cbxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12" }));
        cbxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxYearActionPerformed(evt);
            }
        });

        cbxSection.setBackground(new java.awt.Color(255, 255, 255));
        cbxSection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxSection.setForeground(new java.awt.Color(0, 0, 0));
        cbxSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diamond", "Emerald", "Ruby", "Jasmin", "Sampaguita", "Waling-Waling", "Lithium", "Sodium", "Potassium", "Gluon", "Muon", "Graviton", "Rigel", "Polaris", "Sirius", "Curie", "Einstein", "Tesla" }));
        cbxSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSectionActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        lblOffense.setFont(new java.awt.Font("Arial Narrow", 1, 22)); // NOI18N
        lblOffense.setForeground(new java.awt.Color(0, 0, 0));
        lblOffense.setText("OFFENSE:");

        txtMinutes.setBackground(new java.awt.Color(255, 255, 255));
        txtMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutesActionPerformed(evt);
            }
        });

        txtClasses.setBackground(new java.awt.Color(255, 255, 255));
        txtClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassesActionPerformed(evt);
            }
        });

        txtDays.setBackground(new java.awt.Color(255, 255, 255));
        txtDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDaysActionPerformed(evt);
            }
        });

        lblMinutes.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblMinutes.setForeground(new java.awt.Color(0, 0, 0));
        lblMinutes.setText("min/s");

        lblDays.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblDays.setForeground(new java.awt.Color(0, 0, 0));
        lblDays.setText("day/s");

        lblClasses.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblClasses.setForeground(new java.awt.Color(0, 0, 0));
        lblClasses.setText("class/es");

        rbtnAbsent.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbtnAbsent.setForeground(new java.awt.Color(0, 0, 0));
        rbtnAbsent.setText("Absent");

        rbtnTardy.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbtnTardy.setForeground(new java.awt.Color(0, 0, 0));
        rbtnTardy.setText("Tardy");

        rbtnCutting.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbtnCutting.setForeground(new java.awt.Color(0, 0, 0));
        rbtnCutting.setText("Cutting");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("-");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("-");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOffense)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnTardy)
                            .addComponent(rbtnAbsent)
                            .addComponent(rbtnCutting))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDays, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinutes)
                    .addComponent(lblDays)
                    .addComponent(lblClasses))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOffense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinutes)
                    .addComponent(rbtnAbsent)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDays)
                    .addComponent(rbtnTardy)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClasses)
                    .addComponent(rbtnCutting)
                    .addComponent(jLabel2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        txtLName.setBackground(new java.awt.Color(255, 255, 255));
        txtLName.setForeground(new java.awt.Color(0, 0, 0));

        txtGName.setBackground(new java.awt.Color(255, 255, 255));
        txtGName.setForeground(new java.awt.Color(0, 0, 0));
        txtGName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGNameActionPerformed(evt);
            }
        });

        txtMI.setBackground(new java.awt.Color(255, 255, 255));
        txtMI.setForeground(new java.awt.Color(0, 0, 0));
        txtMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMIActionPerformed(evt);
            }
        });

        lblLName.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lblLName.setForeground(new java.awt.Color(0, 0, 0));
        lblLName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLName.setText("Last Name");

        lblGName.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lblGName.setForeground(new java.awt.Color(0, 0, 0));
        lblGName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGName.setText("Given Name");

        lblMI.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lblMI.setForeground(new java.awt.Color(0, 0, 0));
        lblMI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMI.setText("M.I.");

        jPanel4.setBackground(new java.awt.Color(229, 229, 229));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        lblSubjects.setFont(new java.awt.Font("Arial Narrow", 1, 22)); // NOI18N
        lblSubjects.setForeground(new java.awt.Color(0, 0, 0));
        lblSubjects.setText("SUBJECT/S:");

        ckbxBio.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxBio.setForeground(new java.awt.Color(0, 0, 0));
        ckbxBio.setText("Biology ");
        ckbxBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxBioActionPerformed(evt);
            }
        });

        ckbxChem.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxChem.setForeground(new java.awt.Color(0, 0, 0));
        ckbxChem.setText("Chemistry");
        ckbxChem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxChemActionPerformed(evt);
            }
        });

        ckbxEng.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxEng.setForeground(new java.awt.Color(0, 0, 0));
        ckbxEng.setText("English ");
        ckbxEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxEngActionPerformed(evt);
            }
        });

        ckbxFil.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxFil.setForeground(new java.awt.Color(0, 0, 0));
        ckbxFil.setText("Filipino ");
        ckbxFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxFilActionPerformed(evt);
            }
        });

        ckbxCS.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxCS.setForeground(new java.awt.Color(0, 0, 0));
        ckbxCS.setText("Computer Science ");
        ckbxCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxCSActionPerformed(evt);
            }
        });

        ckbxMath.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxMath.setForeground(new java.awt.Color(0, 0, 0));
        ckbxMath.setText("Mathematics ");
        ckbxMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxMathActionPerformed(evt);
            }
        });

        ckbxPEHM.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxPEHM.setForeground(new java.awt.Color(0, 0, 0));
        ckbxPEHM.setText("P.E.H.M ");
        ckbxPEHM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxPEHMActionPerformed(evt);
            }
        });

        ckbxPhy.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxPhy.setForeground(new java.awt.Color(0, 0, 0));
        ckbxPhy.setText("Physics ");
        ckbxPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxPhyActionPerformed(evt);
            }
        });

        ckbxSS.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxSS.setForeground(new java.awt.Color(0, 0, 0));
        ckbxSS.setText("Social Science ");
        ckbxSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxSSActionPerformed(evt);
            }
        });

        ckbxElective.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxElective.setForeground(new java.awt.Color(0, 0, 0));
        ckbxElective.setText("Elective ");
        ckbxElective.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxElectiveActionPerformed(evt);
            }
        });

        ckbxValEd.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxValEd.setForeground(new java.awt.Color(0, 0, 0));
        ckbxValEd.setText("Values Education ");
        ckbxValEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxValEdActionPerformed(evt);
            }
        });

        ckbxRes.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ckbxRes.setForeground(new java.awt.Color(0, 0, 0));
        ckbxRes.setText("Research");
        ckbxRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbxCS)
                            .addComponent(ckbxEng)
                            .addComponent(ckbxChem)
                            .addComponent(ckbxBio)))
                    .addComponent(lblSubjects))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbxMath)
                    .addComponent(ckbxPEHM)
                    .addComponent(ckbxPhy)
                    .addComponent(ckbxFil))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbxRes)
                    .addComponent(ckbxValEd)
                    .addComponent(ckbxElective)
                    .addComponent(ckbxSS))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbxBio)
                    .addComponent(ckbxFil)
                    .addComponent(ckbxRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbxChem)
                    .addComponent(ckbxMath)
                    .addComponent(ckbxSS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbxCS)
                    .addComponent(ckbxPEHM)
                    .addComponent(ckbxElective))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbxEng)
                    .addComponent(ckbxPhy)
                    .addComponent(ckbxValEd))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblIncDates.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblIncDates.setForeground(new java.awt.Color(0, 0, 0));
        lblIncDates.setText("Inclusive date/s:");

        txtIncDates.setBackground(new java.awt.Color(255, 255, 255));
        txtIncDates.setForeground(new java.awt.Color(0, 0, 0));
        txtIncDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIncDatesActionPerformed(evt);
            }
        });

        lblReason.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblReason.setForeground(new java.awt.Color(0, 0, 0));
        lblReason.setText("Reason:");

        lblAttach.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblAttach.setForeground(new java.awt.Color(0, 0, 0));
        lblAttach.setText("Attachments:");

        ckbxMedCert.setFont(new java.awt.Font("Segoe UI Historic", 0, 17)); // NOI18N
        ckbxMedCert.setForeground(new java.awt.Color(0, 0, 0));
        ckbxMedCert.setText("Medical Certificate");
        ckbxMedCert.setMargin(new java.awt.Insets(1, 1, 1, 1));

        ckbxLetter.setFont(new java.awt.Font("Segoe UI Historic", 0, 17)); // NOI18N
        ckbxLetter.setForeground(new java.awt.Color(0, 0, 0));
        ckbxLetter.setText("Letter from Parent/Guardian");
        ckbxLetter.setMargin(new java.awt.Insets(1, 1, 1, 1));

        lblCertBy.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblCertBy.setForeground(new java.awt.Color(0, 0, 0));
        lblCertBy.setText("Certified by:");

        ckbxHSU.setFont(new java.awt.Font("Segoe UI Historic", 1, 17)); // NOI18N
        ckbxHSU.setForeground(new java.awt.Color(0, 0, 0));
        ckbxHSU.setText("HSU");
        ckbxHSU.setMargin(new java.awt.Insets(1, 1, 1, 1));
        ckbxHSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxHSUActionPerformed(evt);
            }
        });

        ckbxGSU.setFont(new java.awt.Font("Segoe UI Historic", 1, 17)); // NOI18N
        ckbxGSU.setForeground(new java.awt.Color(0, 0, 0));
        ckbxGSU.setText("GSU");
        ckbxGSU.setMargin(new java.awt.Insets(1, 1, 1, 1));
        ckbxGSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxGSUActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(229, 229, 229));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        lblRegistrar.setFont(new java.awt.Font("Arial Narrow", 1, 22)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistrar.setText("Registrar:");

        lblDateIssued.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblDateIssued.setForeground(new java.awt.Color(0, 0, 0));
        lblDateIssued.setText("Date issued:");

        txtMonth.setBackground(new java.awt.Color(255, 255, 255));
        txtMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthActionPerformed(evt);
            }
        });

        txtDay.setBackground(new java.awt.Color(255, 255, 255));
        txtDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayActionPerformed(evt);
            }
        });

        txtYear.setBackground(new java.awt.Color(255, 255, 255));
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("/");

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("/");

        lblMonth.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblMonth.setText("mm");

        lblDate.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblDate.setText("dd");

        lblYear.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        lblYear.setText("yy");

        rbtnExcused.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbtnExcused.setForeground(new java.awt.Color(0, 0, 0));
        rbtnExcused.setText("Excused");
        rbtnExcused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnExcusedActionPerformed(evt);
            }
        });

        rbtnUnexcused.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbtnUnexcused.setForeground(new java.awt.Color(0, 0, 0));
        rbtnUnexcused.setText("Unexcused");
        rbtnUnexcused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnUnexcusedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDateIssued)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(rbtnExcused)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnUnexcused)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel19))
                    .addComponent(lblMonth))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDate)))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateIssued, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblRegistrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnExcused)
                            .addComponent(rbtnUnexcused))))
                .addContainerGap())
        );

        btnSubmit.setForeground(new java.awt.Color(0, 0, 0));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        txtAreaReason.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaReason.setColumns(20);
        txtAreaReason.setLineWrap(true);
        txtAreaReason.setRows(5);
        txtAreaReason.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaReason);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lblLName)
                        .addGap(82, 82, 82)
                        .addComponent(lblGName)
                        .addGap(59, 59, 59)
                        .addComponent(lblMI)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(260, 260, 260))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHdr1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblIncDates)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIncDates))
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblReason)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblCertBy)
                                    .addGap(61, 61, 61))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblAttach)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckbxMedCert)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(ckbxLetter)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ckbxHSU)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ckbxGSU))))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblText2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHdr2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtGName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMI, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(103, 103, 103)
                                    .addComponent(lblYrSec)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxSection, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHdr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHdr2)
                .addGap(22, 22, 22)
                .addComponent(lblText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText2)
                    .addComponent(lblYrSec)
                    .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLName)
                    .addComponent(lblGName)
                    .addComponent(lblMI))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncDates)
                            .addComponent(txtIncDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAttach)
                            .addComponent(ckbxMedCert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCertBy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReason)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbxHSU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbxGSU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbxLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 82, 29, 63);
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1067, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGNameActionPerformed

    private void txtMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMIActionPerformed

    private void cbxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxYearActionPerformed
        // TODO add your handling code here:
        try {
            if (cbxYear.getSelectedItem().equals("7")){

                cbxSection.removeAllItems();
                cbxSection.setSelectedItem(null);
                cbxSection.addItem("Diamond");
                cbxSection.addItem("Emerald");
                cbxSection.addItem("Ruby");

            } else if (cbxYear.getSelectedItem().equals("8")){

                cbxSection.removeAllItems();
                cbxSection.setSelectedItem(null);
                cbxSection.addItem("Jasmin");
                cbxSection.addItem("Sampaguita");
                cbxSection.addItem("Waling-Waling");

            } else if (cbxYear.getSelectedItem().equals("9")){

                cbxSection.removeAllItems();
                cbxSection.setSelectedItem(null);
                cbxSection.addItem("Lithium");
                cbxSection.addItem("Potassium");
                cbxSection.addItem("Sodium");

            } else if (cbxYear.getSelectedItem().equals("10")){

                cbxSection.removeAllItems();
                cbxSection.setSelectedItem(null);
                cbxSection.addItem("Gluon");
                cbxSection.addItem("Graviton");
                cbxSection.addItem("Muon");

            } else if (cbxYear.getSelectedItem().equals("11")){

                cbxSection.removeAllItems();
                cbxSection.setSelectedItem(null);
                cbxSection.addItem("Polaris");
                cbxSection.addItem("Rigel");
                cbxSection.addItem("Serius");

            } else if (cbxYear.getSelectedItem().equals("12")){

                cbxSection.removeAllItems();
                cbxSection.setSelectedItem(null);
                cbxSection.addItem("Curie");
                cbxSection.addItem("Einstein");
                cbxSection.addItem("Tesla");

            }
            } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cbxYearActionPerformed

    private void cbxSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSectionActionPerformed

    private void ckbxBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxBioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxBioActionPerformed

    private void txtClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassesActionPerformed

    private void txtDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDaysActionPerformed

    private void ckbxChemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxChemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxChemActionPerformed

    private void ckbxCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxCSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxCSActionPerformed

    private void ckbxEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxEngActionPerformed

    private void ckbxFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxFilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxFilActionPerformed

    private void ckbxMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxMathActionPerformed

    private void ckbxPEHMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxPEHMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxPEHMActionPerformed

    private void ckbxPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxPhyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxPhyActionPerformed

    private void ckbxSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxSSActionPerformed

    private void ckbxElectiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxElectiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxElectiveActionPerformed

    private void ckbxValEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxValEdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxValEdActionPerformed

    private void ckbxResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxResActionPerformed

    private void txtIncDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIncDatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIncDatesActionPerformed

    private void txtMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutesActionPerformed

    private void ckbxHSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxHSUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxHSUActionPerformed

    private void ckbxGSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxGSUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxGSUActionPerformed

    private void txtMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Student name
        String lastName = capitalizeEachWord(txtLName.getText().trim());
        String firstName = capitalizeEachWord(txtGName.getText().trim());
        String middleInitial = txtMI.getText().trim().toUpperCase(); // or capitalize if needed

        String fullName = null;
        StringBuilder errorMsg = new StringBuilder();

        // Check if any of the fields are empty
        if (lastName.isEmpty()) {
            errorMsg.append("• Last Name is required.\n");
        }
        if (firstName.isEmpty()) {
            errorMsg.append("• First Name is required.\n");
        }
        if (middleInitial.isEmpty()) {
            errorMsg.append("• Middle Initial is required.\n");
        }
        if (!middleInitial.isEmpty()) {
        if (middleInitial.length() == 1) {
            middleInitial += ".";
        } else if (middleInitial.length() == 2 && middleInitial.charAt(1) != '.') {
            middleInitial = middleInitial.charAt(0) + ".";
        }
        }

        // Show error if any field is empty
        if (errorMsg.length() > 0) {
            JOptionPane.showMessageDialog(null, "Please correct the following:\n" + errorMsg);
            return;
        }

        try {
            // Validate character content
            if (!lastName.matches("[a-zA-Z\\s\\-']+")) {
                throw new IllegalArgumentException("Last Name must contain only letters, spaces, hyphens, or apostrophes.");
            }
            if (!firstName.matches("[a-zA-Z\\s\\-']+")) {
                throw new IllegalArgumentException("First Name must contain only letters, spaces, hyphens, or apostrophes.");
            }
            if (!middleInitial.matches("[a-zA-Z](\\.)?")) {
                throw new IllegalArgumentException("Middle Initial must be a single letter (with optional period).");
            }

            // Capitalize each word in first and last name
            lastName = capitalizeEachWord(lastName);
            firstName = capitalizeEachWord(firstName);

            // Capitalize middle initial only
            middleInitial = middleInitial.toUpperCase();

            // Construct full name
            fullName = lastName + ", " + firstName + " " + middleInitial;

            // Optional: store fullName somewhere or display
            System.out.println("Formatted Full Name: " + fullName);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }

        

        // Year-Section
        String year = (String) cbxYear.getSelectedItem();
        String section = (String) cbxSection.getSelectedItem();
        
        String yearAndSection = year + " - " + section;
        
        // Offense
        ButtonGroup offenseGroup = new ButtonGroup();
        offenseGroup.add(rbtnAbsent);
        offenseGroup.add(rbtnTardy);
        offenseGroup.add(rbtnCutting);
        String offense = null;

        try {
            if (rbtnAbsent.isSelected()) {
                offense = rbtnAbsent.getText();
            } else if (rbtnTardy.isSelected()) {
                offense = rbtnTardy.getText();
            } else if (rbtnCutting.isSelected()) {
                offense = rbtnCutting.getText();
            } else {
                throw new IllegalArgumentException("Please select only one offense.");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred while selecting an offense: " + e.getMessage());
            return;
        }


        // Minutes, days, and classes
        float days = 0;
        int minute = 0, classes = 0;

        try {
            minute = Integer.parseInt(txtMinutes.getText().trim());
            days = Float.parseFloat(txtDays.getText().trim());
            classes = Integer.parseInt(txtClasses.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Minute, Days (decimal), and Classes.");
            return;
        }
        
        // Missed subjects
        String subjects = null;

        try {
            List<String> selectedSubjects = new ArrayList<>();

            if (ckbxBio != null && ckbxBio.isSelected()) selectedSubjects.add(" • " + ckbxBio.getText());
            if (ckbxChem != null && ckbxChem.isSelected()) selectedSubjects.add(" • " + ckbxChem.getText());
            if (ckbxCS != null && ckbxCS.isSelected()) selectedSubjects.add(" • " + ckbxCS.getText());
            if (ckbxEng != null && ckbxEng.isSelected()) selectedSubjects.add(" • " + ckbxEng.getText());
            if (ckbxFil != null && ckbxFil.isSelected()) selectedSubjects.add(" • " + ckbxFil.getText());
            if (ckbxMath != null && ckbxMath.isSelected()) selectedSubjects.add(" • " + ckbxMath.getText());
            if (ckbxPEHM != null && ckbxPEHM.isSelected()) selectedSubjects.add(" • " + ckbxPEHM.getText());
            if (ckbxPhy != null && ckbxPhy.isSelected()) selectedSubjects.add(" • " + ckbxPhy.getText());
            if (ckbxRes != null && ckbxRes.isSelected()) selectedSubjects.add(" • " + ckbxRes.getText());
            if (ckbxSS != null && ckbxSS.isSelected()) selectedSubjects.add(" • " + ckbxSS.getText());
            if (ckbxElective != null && ckbxElective.isSelected()) selectedSubjects.add(" • " + ckbxElective.getText());
            if (ckbxValEd != null && ckbxValEd.isSelected()) selectedSubjects.add(" • " + ckbxValEd.getText());

            if (selectedSubjects.isEmpty()) {
                throw new IllegalArgumentException("Please select at least one subject.");
            }

            subjects = String.join("\n", selectedSubjects);  // Join with newline, or use ", " if preferred

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return; // Stop further execution
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred while selecting subjects: " + e.getMessage());
            return;
        }

        // Inclusive dates
        String inclusiveDates = txtIncDates.getText().trim();
        if (inclusiveDates.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter inclusive dates.");
        return;
        }
        
        // Reason
        String reason = txtAreaReason.getText().trim();
        if (reason.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter the reason for the said offense/s.");
        return;
        }
        
        // Attachments
        String attachment = null;
        try {
            List<String> selectedAttachment = new ArrayList<>();

            if (ckbxMedCert.isSelected()) selectedAttachment.add(" • " + ckbxMedCert.getText());
            if (ckbxLetter.isSelected()) selectedAttachment.add(" • " + ckbxLetter.getText());

            if (selectedAttachment.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please select at least one attachment.");
                return; // stop further processing
            }

            attachment = String.join("\n", selectedAttachment);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error retrieving attachments: " + e.getMessage());
            return;
        }

        // Certified by
        String certified = null;
        try {
            List<String> certifiedBy = new ArrayList<>();

            if (ckbxHSU.isSelected()) certifiedBy.add(" • " + ckbxHSU.getText());
            if (ckbxGSU.isSelected()) certifiedBy.add(" • " + ckbxGSU.getText());

            if (certifiedBy.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please select who certified the document.");
                return; // stop further processing
            }

            certified = String.join("\n", certifiedBy);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error retrieving certification info: " + e.getMessage());
            return;
        }

        
        // Registrar
        ButtonGroup excusedUnexcused = new ButtonGroup();
        excusedUnexcused.add(rbtnExcused);
        excusedUnexcused.add(rbtnUnexcused);
        String registrar = null;

        try {
            if (rbtnExcused.isSelected()) {
                registrar = rbtnExcused.getText();
            } else if (rbtnUnexcused.isSelected()) {
                registrar = rbtnUnexcused.getText();
            } else {
                throw new IllegalArgumentException("Please select 'Excused' OR 'Unexcused'.");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred while selecting an offense: " + e.getMessage());
            return;
        }
        
       
        // Date Issued
        String mm = txtMonth.getText().trim();
        String dd = txtDay.getText().trim();
        String yy = txtYear.getText().trim();
        String dateIssued = null;

        // Basic numeric validation
        if (!mm.matches("\\d{1,2}") || !dd.matches("\\d{1,2}") || !yy.matches("\\d{2,4}")) {
            JOptionPane.showMessageDialog(null, "Please enter valid numeric values for date issued.");
            return;
        }

        // Normalize values
        if (mm.length() == 1) mm = "0" + mm;
        if (dd.length() == 1) dd = "0" + dd;
        if (yy.length() == 2) yy = "20" + yy; // Convert 25 to 2025

        String fullDate = yy + "-" + mm + "-" + dd; // format as YYYY-MM-DD

        // Check if it's a valid date
        try {
            LocalDate parsedDate = LocalDate.of(Integer.parseInt(yy), Integer.parseInt(mm), Integer.parseInt(dd));
            dateIssued = parsedDate.format(DateTimeFormatter.ofPattern("MM/dd/yy"));
        } catch (DateTimeException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid date. Please enter a valid calendar date.");
            return;
        }


        // Database
        String url = "jdbc:mysql://localhost:3306/oas_database";
        String user = "root";
        String password = "mysql-DB1502";
        
        // Inserting input to database
        String sql = "INSERT INTO student_data (student_name, year_and_section, offense, minutes, days, classes, missed_subjects, inclusive_dates, reason, attachments, certified_by, registrar, date_issued) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        
        try (Connection conn = DriverManager.getConnection(url, user, password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {

           // Set both parameters (this prevents the "parameter 2" error)
           stmt.setString(1, fullName);
           stmt.setString(2, yearAndSection);
           stmt.setString(3, offense);
           stmt.setInt(4, minute);
           stmt.setFloat(5, days);
           stmt.setInt(6, classes);
           stmt.setString(7, subjects); 
           stmt.setString(8, inclusiveDates); 
           stmt.setString(9, reason); 
           stmt.setString(10, attachment);
           stmt.setString(11, certified); 
           stmt.setString(12, registrar);
           stmt.setString(13, dateIssued);


           stmt.executeUpdate();
           conn.close();
           JOptionPane.showMessageDialog(null, "RECORD SAVED:\n" + "Student Name: " + fullName + "\n" + "Year and Section: " + yearAndSection + "\n" + "Offense: " + offense
                                         + "\n" + "Minute/s: " + minute + "\n" + "Day/s: " + days + "\n" + "Class/es: " + classes + "\n" + "Subject/s missed: " + "\n" + subjects + "\n" + "Inclusive Dates: " + inclusiveDates 
                                         + "\n" + "Reason: " + reason + "\n" + "Attachment/s: " + "\n" + attachment + "\n" + "Certified By: " + "\n" + certified + "\n" + "Student is [" + registrar + "]" + "\n" + "Date Issued: " + dateIssued);

       } catch (SQLException ex) {
           // This catches and shows the exact SQL error
           ex.printStackTrace(); // Shows error in the console
           JOptionPane.showMessageDialog(null, "Error saving record:\n" + ex.getMessage());
       }


    }//GEN-LAST:event_btnSubmitActionPerformed
// --- Helper method to capitalize each word ---
        public String capitalizeEachWord(String input) {
        String[] words = input.trim().split("\\s+");
        StringBuilder sb = new StringBuilder();
        for (String word : words) {
            if (!word.isEmpty()) {
                sb.append(Character.toUpperCase(word.charAt(0)))
                  .append(word.substring(1).toLowerCase())
                  .append(" ");
            }
        }
        return sb.toString().trim();
    }

    private void rbtnUnexcusedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnUnexcusedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnUnexcusedActionPerformed

    private void rbtnExcusedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnExcusedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnExcusedActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Resetting the text fields
    txtLName.setText("");
    txtGName.setText("");
    txtMI.setText("");    
    txtMinutes.setText("");
    txtDays.setText("");
    txtClasses.setText("");
    txtIncDates.setText("");
    txtAreaReason.setText("");
    txtMonth.setText("");
    txtDay.setText("");
    txtYear.setText("");

    // Resetting ComboBoxes
    cbxYear.setSelectedIndex(-1);  // Deselects item in combobox
    cbxSection.setSelectedIndex(-1);    // Deselects item in combobox

    // Resetting Checkboxes
    ckbxMedCert.setSelected(false);
    ckbxLetter.setSelected(false);
    ckbxHSU.setSelected(false);
    ckbxGSU.setSelected(false);
    
    // Reset all subject checkboxes
    JCheckBox[] subjectCheckBoxes = {
        ckbxBio, ckbxChem, ckbxCS, ckbxEng, ckbxFil,
        ckbxMath, ckbxPEHM, ckbxPhy, ckbxRes,
        ckbxSS, ckbxElective, ckbxValEd
    };

    for (JCheckBox checkBox : subjectCheckBoxes) {
        if (checkBox != null) checkBox.setSelected(false);
    }

    // Resetting Radio Buttons (if you have any)
//    excusedUnexcused.clearSelection();  
//    offenseGroup.clearSelection();
    
    rbtnAbsent.setSelected(false);
    rbtnTardy.setSelected(false);
    rbtnExcused.setSelected(false);
    rbtnExcused.setSelected(false);
    rbtnUnexcused.setSelected(false);



    // You can also reset any other component as necessary
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmissionSlipForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmissionSlipForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmissionSlipForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmissionSlipForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmissionSlipForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbxSection;
    private javax.swing.JComboBox<String> cbxYear;
    private javax.swing.JCheckBox ckbxBio;
    private javax.swing.JCheckBox ckbxCS;
    private javax.swing.JCheckBox ckbxChem;
    private javax.swing.JCheckBox ckbxElective;
    private javax.swing.JCheckBox ckbxEng;
    private javax.swing.JCheckBox ckbxFil;
    private javax.swing.JCheckBox ckbxGSU;
    private javax.swing.JCheckBox ckbxHSU;
    private javax.swing.JCheckBox ckbxLetter;
    private javax.swing.JCheckBox ckbxMath;
    private javax.swing.JCheckBox ckbxMedCert;
    private javax.swing.JCheckBox ckbxPEHM;
    private javax.swing.JCheckBox ckbxPhy;
    private javax.swing.JCheckBox ckbxRes;
    private javax.swing.JCheckBox ckbxSS;
    private javax.swing.JCheckBox ckbxValEd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAttach;
    private javax.swing.JLabel lblCertBy;
    private javax.swing.JLabel lblClasses;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateIssued;
    private javax.swing.JLabel lblDays;
    private javax.swing.JLabel lblGName;
    private javax.swing.JLabel lblHdr1;
    private javax.swing.JLabel lblHdr2;
    private javax.swing.JLabel lblIncDates;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblMI;
    private javax.swing.JLabel lblMinutes;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblOffense;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSubjects;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblText2;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYrSec;
    private javax.swing.JRadioButton rbtnAbsent;
    private javax.swing.JRadioButton rbtnCutting;
    private javax.swing.JRadioButton rbtnExcused;
    private javax.swing.JRadioButton rbtnTardy;
    private javax.swing.JRadioButton rbtnUnexcused;
    private javax.swing.JTextArea txtAreaReason;
    private javax.swing.JTextField txtClasses;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtDays;
    private javax.swing.JTextField txtGName;
    private javax.swing.JTextField txtIncDates;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMI;
    private javax.swing.JTextField txtMinutes;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
