/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oas_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AykAyz
 */
public class TeacherSignInPage extends javax.swing.JFrame {

    /**
     * Creates new form TeacherSignInPage
     */
    public TeacherSignInPage() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);  
        initComponents();
        cbxGLevels.setSelectedItem(null);
        cbxElecSubj.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        cbxSubjHandl = new javax.swing.JComboBox<>();
        cbxGLevels = new javax.swing.JComboBox<>();
        lblSubjHandl = new javax.swing.JLabel();
        lblGLevels = new javax.swing.JLabel();
        cbxYesOrNo = new javax.swing.JComboBox<>();
        lblElecSubj = new javax.swing.JLabel();
        lblIfYesOrNo = new javax.swing.JLabel();
        cbxElecSubj = new javax.swing.JComboBox<>();
        btnSignIn = new javax.swing.JButton();
        lblSecHandl1 = new javax.swing.JLabel();
        lblSecHandl2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSecHandl2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSecHandl1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(206, 206, 206));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 421));

        lblName.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Name:");

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.setText("Last Name, First Name M.I.");

        lblUsername.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setText("Username:");

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 0, 0));

        lblPassword.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblPassword.setText("Password:");

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        cbxSubjHandl.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        cbxSubjHandl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTEGRATED SCIENCE", "BIOLOGY", "CHEMISTRY", "PHYSICS", "MATHEMATICS", "ENGLISH", "FILIPINO", "SOCIAL SCIENCE", "P.E.H.M.", "VALED", "ADTECH", "STATISTICS", "(STEM) RESEARCH", "COMPUTER SCIENCE", "EARTH SCIENCE" }));
        cbxSubjHandl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSubjHandlActionPerformed(evt);
            }
        });

        cbxGLevels.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        cbxGLevels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12" }));
        cbxGLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGLevelsActionPerformed(evt);
            }
        });

        lblSubjHandl.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblSubjHandl.setForeground(new java.awt.Color(0, 0, 0));
        lblSubjHandl.setText("Subject handling:");

        lblGLevels.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblGLevels.setForeground(new java.awt.Color(0, 0, 0));
        lblGLevels.setText("Grade level handling:");

        cbxYesOrNo.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        cbxYesOrNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        cbxYesOrNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxYesOrNoActionPerformed(evt);
            }
        });

        lblElecSubj.setBackground(new java.awt.Color(0, 0, 0));
        lblElecSubj.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblElecSubj.setForeground(new java.awt.Color(0, 0, 0));
        lblElecSubj.setText("Are you handling elective subjects?");

        lblIfYesOrNo.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblIfYesOrNo.setForeground(new java.awt.Color(0, 0, 0));
        lblIfYesOrNo.setText("If yes, subject handling:");

        cbxElecSubj.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        cbxElecSubj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGINEERING SCIENCE 1", "ENGINEERING SCIENCE 2", "TECHNOLOGY 1", "TECHNOLOGY 2", "AGRICULTURE 1", "AGRICULTURE 2" }));
        cbxElecSubj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxElecSubjActionPerformed(evt);
            }
        });

        btnSignIn.setBackground(new java.awt.Color(0, 102, 255));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignIn.setText("SIGN IN");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        lblSecHandl1.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblSecHandl1.setForeground(new java.awt.Color(0, 0, 0));
        lblSecHandl1.setText("Section/s Handling:");
        lblSecHandl1.setAlignmentY(0.0F);

        lblSecHandl2.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblSecHandl2.setForeground(new java.awt.Color(0, 0, 0));
        lblSecHandl2.setText("Section/s Handling:");
        lblSecHandl2.setAlignmentY(0.0F);

        txtAreaSecHandl2.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaSecHandl2.setColumns(20);
        txtAreaSecHandl2.setLineWrap(true);
        txtAreaSecHandl2.setRows(5);
        txtAreaSecHandl2.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaSecHandl2);

        txtAreaSecHandl1.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaSecHandl1.setColumns(20);
        txtAreaSecHandl1.setLineWrap(true);
        txtAreaSecHandl1.setRows(5);
        txtAreaSecHandl1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAreaSecHandl1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbxGLevels, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblGLevels)
                                    .addGap(12, 12, 12))
                                .addComponent(cbxSubjHandl, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblSecHandl1)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbxYesOrNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxElecSubj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(lblIfYesOrNo))))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSecHandl2)
                                .addGap(46, 46, 46))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSubjHandl)
                        .addGap(37, 37, 37)
                        .addComponent(lblElecSubj)))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword)
                    .addComponent(lblName))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubjHandl)
                    .addComponent(lblElecSubj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSubjHandl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxYesOrNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGLevels)
                    .addComponent(lblIfYesOrNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxGLevels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxElecSubj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecHandl1)
                    .addComponent(lblSecHandl2))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 85, 24, 85);
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(698, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSubjHandlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSubjHandlActionPerformed
        // TODO add your handling code here:
        try {
            if (cbxSubjHandl.getSelectedItem().equals("INTEGRATED SCIENCE")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");

            } else if (cbxSubjHandl.getSelectedItem().equals("BIOLOGY")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("CHEMISTRY")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("PHYSICS")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("MATHEMATICS")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("ENGLISH")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("FILIPINO")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("SOCIAL SCIENCE")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("P.E.H.M.")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");

            } else if (cbxSubjHandl.getSelectedItem().equals("VALED")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");

            } else if (cbxSubjHandl.getSelectedItem().equals("ADTECH")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");

            } else if (cbxSubjHandl.getSelectedItem().equals("STATISTICS")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("9");

            } else if (cbxSubjHandl.getSelectedItem().equals("(STEM) RESEARCH")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("COMPUTER SCIENCE")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);
                cbxGLevels.addItem("7");
                cbxGLevels.addItem("8");
                cbxGLevels.addItem("9");
                cbxGLevels.addItem("10");
                cbxGLevels.addItem("11");
                cbxGLevels.addItem("12");

            } else if (cbxSubjHandl.getSelectedItem().equals("EARTH SCIENCE")){

                cbxGLevels.removeAllItems();
                cbxGLevels.setSelectedItem(null);                        
                cbxGLevels.addItem("8");

            } 
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cbxSubjHandlActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void cbxYesOrNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxYesOrNoActionPerformed
        // TODO add your handling code here:
        try {
            if (cbxYesOrNo.getSelectedItem().equals("YES")){

                    cbxElecSubj.removeAllItems();
                    cbxElecSubj.setSelectedItem(null);                        
                    cbxElecSubj.addItem("ENGINEERING SCIENCE 1");
                    cbxElecSubj.addItem("ENGINEERING SCIENCE 2");
                    cbxElecSubj.addItem("TECHNOLOGY 1");
                    cbxElecSubj.addItem("TECHNOLOGY 2");
                    cbxElecSubj.addItem("AGRICULTURE 1");
                    cbxElecSubj.addItem("AGRICULTURE 2");

                } else if (cbxYesOrNo.getSelectedItem().equals("NO")){

                    cbxElecSubj.removeAllItems();
                    cbxElecSubj.setSelectedItem(null);                        
                    cbxElecSubj.addItem("N/A");

                } 
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cbxYesOrNoActionPerformed

    private void cbxElecSubjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxElecSubjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxElecSubjActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // Name, Username, Password
        String name = txtName.getText().trim();
        String username = txtUsername.getText().trim();
        String passwordT = txtPassword.getText().trim();
        
        // Grade and Section handling
        String subjHandling = (String) cbxSubjHandl.getSelectedItem();
        String yearHandling = (String) cbxGLevels.getSelectedItem();
        String section = txtAreaSecHandl1.getText().trim();

        // Elective
        String yesORno = (String) cbxYesOrNo.getSelectedItem();
        String elecSubject = (String) cbxElecSubj.getSelectedItem();
        String sectionElec = txtAreaSecHandl2.getText().trim();
        
        // Database
        String url = "jdbc:mysql://localhost:3306/oas_database";
        String user = "root";
        String password = "mysql-DB1502";
        
        // Inserting input to database
        String sql = "INSERT INTO teacher_data (teacher_name, username, teacher_password, subject_handling, year_handling, section_handling, elective_handling, elective_subject, elective_section) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);";

        
        try (Connection conn = DriverManager.getConnection(url, user, password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {

           // Set both parameters (this prevents the "parameter 2" error)
           stmt.setString(1, name);
           stmt.setString(2, username);
           stmt.setString(3, passwordT);
           stmt.setString(4, subjHandling);
           stmt.setString(5, yearHandling);
           stmt.setString(6, section);
           stmt.setString(7, yesORno); 
           stmt.setString(8, elecSubject); 
           stmt.setString(9, sectionElec); 
           


           stmt.executeUpdate();
           conn.close();
           JOptionPane.showMessageDialog(null, "Record saved:\n" + "Name of Teacher: " + name + "\n" + "Username: " + username + "\n" + "Password: " + passwordT
                                         + "\n" + "Subject Handling: " + subjHandling + "\n" + "Grade Level Handling: " + yearHandling + "\n" + "Section/s: " + section + "\n" + "Handling Elective Subject?: " + yesORno + "\n" + "Elective Subject: " + elecSubject 
                                         + "\n" + "Section/s: " + sectionElec);

       } catch (SQLException ex) {
           // This catches and shows the exact SQL error
           ex.printStackTrace(); // Shows error in the console
           JOptionPane.showMessageDialog(null, "Error saving record:\n" + ex.getMessage());
       }


        
    }//GEN-LAST:event_btnSignInActionPerformed

    private void cbxGLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGLevelsActionPerformed
        // TODO add your handling code here:
        //my code contains 3 jtextfields, name, username, and password. it also has 4 
//        try {
//            if (cbxSubjHandl.getSelectedItem().equals("INTEGRATED SCIENCE") && cbxGLevels.getSelectedItem().equals("7")){
//
//                cbxSecHandl1.removeAllItems();
//                cbxSecHandl1.setSelectedItem(null);
//                cbxSecHandl1.addItem("Diamond");
//                cbxSecHandl1.addItem("Emerald");
//                cbxSecHandl1.addItem("Ruby");
//
//            } else if (cbxSubjHandl.getSelectedItem().equals("INTEGRATED SCIENCE") && cbxGLevels.getSelectedItem().equals("8")){
//
//                cbxSecHandl1.removeAllItems();
//                cbxSecHandl1.setSelectedItem(null);
//                cbxSecHandl1.addItem("Jasmin");
//                cbxSecHandl1.addItem("Sampaguita");
//                cbxSecHandl1.addItem("Waling-Waling");
//
//            }  else if (cbxSubjHandl.getSelectedItem().equals("Biology") || cbxGLevels.getSelectedItem().equals("8")){
//
//                cbxSecHandl1.removeAllItems();
//                cbxSecHandl1.setSelectedItem(null);
//                cbxSecHandl1.addItem("Jasmin");
//                cbxSecHandl1.addItem("Sampaguita");
//                cbxSecHandl1.addItem("Waling-Waling");
//
//            } 
//        }catch (Exception e ) {
//        System.out.println(e);
//        
//        }
    }//GEN-LAST:event_cbxGLevelsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherSignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherSignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherSignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherSignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherSignInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JComboBox<String> cbxElecSubj;
    private javax.swing.JComboBox<String> cbxGLevels;
    private javax.swing.JComboBox<String> cbxSubjHandl;
    private javax.swing.JComboBox<String> cbxYesOrNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblElecSubj;
    private javax.swing.JLabel lblGLevels;
    private javax.swing.JLabel lblIfYesOrNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSecHandl1;
    private javax.swing.JLabel lblSecHandl2;
    private javax.swing.JLabel lblSubjHandl;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextArea txtAreaSecHandl1;
    private javax.swing.JTextArea txtAreaSecHandl2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
